### ISSUE TITLE
Issue pasting directly to Skedge window

### ISSUE THREAD

**Issue by gorjious** [Mark2Mark/Skedge#3]
Pasting snippets directly into the Skedge window does something strange to the colours (the image in unhighlighted). If I paste the snippet into a code editor then into Skedge, it works fine.

<img width="753" alt="screen shot 2018-06-27 at 15 24 57" src="https://user-images.githubusercontent.com/23149420/42000641-8c34cb0a-7a1e-11e8-974a-86d3dc0e34fc.png">

**Comment by Mark2Mark** [comment]
Yes, I am aware of that issue. Thanks for reporting though. I’ll try to find a solution.

**Comment by schriftgestalt** [comment]
In the main syntax coloring method before you set the color and default font, get to the NSTextView.textstorage() and set it’s attributs to an empty dict.

**Comment by Mark2Mark** [comment]
@schriftgestalt You know that you are a true Genius, right? 😃👍 
Thank you so much!

I made it work with this:
```
textStorage = self.textView.textStorage()
textStorage.setAttributes_range_(  {}, ( 0,textStorage.length() ))
```
Lovely!
