### ISSUE TITLE
Crashes Glyphs on startup

### ISSUE THREAD

**Issue by Mark2Mark** [Mark2Mark/Skedge#6]
It used to work on my Mojave Mac even in Glyphs 3, but on the M1 Mac it crashes. Incredibly hard to debug as I cannot get any prints to the Macro Panel

**Comment by Mark2Mark** [comment]
@schriftgestalt @mekkablue 

I am desperate. It might have to do sth with the [python version, as mentioned here](https://forum.glyphsapp.com/t/vanilla-broken-in-glyphs-3061-and-previous/17737/4)?

This might be in connection to the current Python brokenness.

**Comment by schriftgestalt** [comment]
Skedge works just fine for me on M1 with python 3.9.1 from python.org.

**Comment by Mark2Mark** [comment]
Solved. My Python framework was corrupt.
Our solution was to reset the GSPythonFrameworkPath:
`defaults delete com.GeorgSeifert.Glyphs3 GSPythonFrameworkPath`
